config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :todos
  

end

app/models/delete_todos.rb
module DeleteTodos
  def self.run
    Todo.where("created_at <= ?", 1.week.ago).destroy_all
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :description
  validates_presence_of :user_id

  after_save :delete_completed_todo

  def expiration_date
    self.created_at+1.week
  end

  def delete_completed_todo
    if self.completed
      self.destroy
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    todos_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.build(todo_params)

    if @todo.save
      redirect_to todos_path, notice: "Your todo has been created successfully."
    else
      flash[:alert] = "Error creating todo. Please try again."
      render :new
    end
  end

  def update
    @todo = Todo.find(params[:id])

    @todo.update_attributes(todo_params)
    render text: "Your todo was successfully updated."
  end

  private

  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="user-info">
      <% if current_user %>
        <%= current_user.email %> | <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %> | <%= link_to 'Sign In', new_user_session_path %>
      <% end %>
    </div>
  </header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h2>My list</h2>

<table>
  <thead>
    <th>Description</th>
    <th>Days left</th>
    <th>Complete</th>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr class="todo_row">
        <td><%= todo.description.capitalize %></td>
        <td><%= distance_of_time_in_words_to_now(todo.expiration_date) %></td>
        <td><%= check_box_tag 'complete', "1", todo.completed, id: "checkbox_#{todo.id}", data: {url: todo_path(todo)} %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Create new todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= form_for @todo do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  
  <%= f.submit 'Save' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Blocitoff:</h1>

<p>A self-destructing to-do list to keep you focused on the things that really matter.</p>